### ISSUE TITLE
error ./install.sh: línea 3: go: no se encontró la orden (line 3: go: command not found)

### ISSUE THREAD

**Issue by gatuno1** [dgrr/GoNordVPN#1]
After clone with $ sudo git clone https://github.com/dgrr/GoNordVPN, and follow the instructi ons, in response to $ sudo -E ./install.sh, appears the error.
My system is Linux Mint 18.3 (Based on Ubuntu Xenial), with python 2.7 installed.
There is some package required? In my system there is no "go" command.

Best regards,
Antonio

**Comment by dgrr** [comment]
Hello,

You need golang to use GoNordVPN. I can make a release if you want.
You can install golang using
```
sudo apt install golang-go
```

**Comment by gatuno1** [comment]
thanks. It works after install golang-1.9-go, because Mint 18.3 by default install golang-1.6-go, that lacks math/bits. Maybe you could add this to prerequisites.
I'll close the issue.
